// Copyright (c) Microsoft. All rights reserved.

using System.Text.Json.Serialization;
using CopilotChat.WebApi.Storage;

namespace CopilotChat.WebApi.Models.Storage;

/// <summary>
/// A file generated by MCP tools that can be downloaded by the user.
/// </summary>
public class GeneratedFile : IStorageEntity
{
  /// <summary>
  /// Unique identifier for the generated file.
  /// </summary>
  [JsonPropertyName("id")]
  public string Id { get; set; } = string.Empty;

  /// <summary>
  /// Partition key for the file (typically the chat ID).
  /// </summary>
  [JsonPropertyName("chatId")]
  public string ChatId { get; set; } = string.Empty;

  /// <summary>
  /// User ID of the user who requested the file generation.
  /// </summary>
  [JsonPropertyName("userId")]
  public string UserId { get; set; } = string.Empty;

  /// <summary>
  /// Original filename.
  /// </summary>
  [JsonPropertyName("fileName")]
  public string FileName { get; set; } = string.Empty;

  /// <summary>
  /// Content type (MIME type) of the file.
  /// </summary>
  [JsonPropertyName("contentType")]
  public string ContentType { get; set; } = "application/octet-stream";

  /// <summary>
  /// The actual file content (base64 encoded for binary files, or plain text).
  /// </summary>
  [JsonPropertyName("content")]
  public string Content { get; set; } = string.Empty;

  /// <summary>
  /// Size of the file in bytes.
  /// </summary>
  [JsonPropertyName("size")]
  public long Size { get; set; }

  /// <summary>
  /// When the file was created.
  /// </summary>
  [JsonPropertyName("createdOn")]
  public DateTimeOffset CreatedOn { get; set; } = DateTimeOffset.UtcNow;

  /// <summary>
  /// When the file expires and should be deleted (optional).
  /// </summary>
  [JsonPropertyName("expiresOn")]
  public DateTimeOffset? ExpiresOn { get; set; }

  /// <summary>
  /// Gets the partition key for the file (ChatId).
  /// </summary>
  public string Partition => this.ChatId;
}

